AWSTemplateFormatVersion: "2010-09-09"
Description: "DynamoDB template for todo-app."

Resources:
  DynamoDB:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "Id"
          AttributeType: "S"
      BillingMode: "PROVISIONED"
      KeySchema:
        - AttributeName: "Id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: "todos"


